"""Harness 9 Epistemic Verification & Grounding Layer.

Provides machine-readable evidence graphs, historical scholarship consensus modeling,
multi-strategy verification engines, and script/visual consistency audit abstractions.
"""

from src.epistemic.graph import (
    ClaimNode,
    CycleDetectedError,
    EdgeNotFoundError,
    EdgeRelation,
    EvidenceGraph,
    EvidenceGraphError,
    EvidenceUnitNode,
    GraphEdge,
    GraphNode,
    GraphNodeType,
    InvalidEdgeError,
    ModalityType,
    NodeNotFoundError,
    PassageNode,
    ProvenanceChain,
    SceneNode,
    ScriptSentenceNode,
    SourceNode,
    VerificationTraceNode,
    VisualElementNode,
)
from src.epistemic.historical_policy import (
    ContradictionRecord,
    HistoricalFraming,
    HistoricalPolicyChecker,
    HistoricalScholarshipPolicyEngine,
    HistoriographicalEvaluationReport,
    HistoriographicalViolationType,
)
from src.epistemic.strategies import (
    BaseVerificationStrategy,
    ContradictionCheckStrategy,
    CrossSourceCorroborationStrategy,
    HistoriographicalCheckStrategy,
    NumericalCheckStrategy,
    QuoteCheckStrategy,
    SourceEntailmentStrategy,
    StrategyExecutionResult,
    TemporalCheckStrategy,
    VerificationStrategy,
)
from src.epistemic.engine import (
    DossierVerificationReport,
    STRATEGY_DISPATCH_MAP,
    VerificationEngine,
    VerificationResult,
)
from src.epistemic.script_verifier import (
    DriftSeverity,
    DriftType,
    ScriptClaimDriftRecord,
    ScriptClaimMapping,
    ScriptSentenceExtraction,
    ScriptSentenceSegmenter,
    ScriptVerificationReport,
    ScriptVerifier,
)
from src.epistemic.visual_verifier import (
    SceneVisualReport,
    VisualDiscrepancy,
    VisualDiscrepancyType,
    VisualInconsistencyRecord,
    VisualSeverity,
    VisualVerificationReport,
    VisualVerifier,
)
from src.epistemic.numerical_pipeline import (
    ChartConfig,
    ChartElement,
    ChartType,
    DeterministicChartRenderer,
    NumericalDataPoint,
    NumericalDataset,
    NumericalDatasetIngestion,
    NumericalInvariantChecker,
    NumericalTransformationRecord,
    NumericalTransformer,
    NumericalVerificationResult,
)

__all__ = [
    # Graph abstractions
    "EvidenceGraph",
    "EvidenceGraphError",
    "CycleDetectedError",
    "NodeNotFoundError",
    "EdgeNotFoundError",
    "InvalidEdgeError",
    "GraphNodeType",
    "ModalityType",
    "EdgeRelation",
    "GraphNode",
    "SourceNode",
    "PassageNode",
    "EvidenceUnitNode",
    "ClaimNode",
    "VerificationTraceNode",
    "SceneNode",
    "ScriptSentenceNode",
    "VisualElementNode",
    "GraphEdge",
    "ProvenanceChain",
    # Historical policy
    "HistoriographicalViolationType",
    "HistoricalFraming",
    "HistoriographicalEvaluationReport",
    "ContradictionRecord",
    "HistoricalPolicyChecker",
    "HistoricalScholarshipPolicyEngine",
    # Strategies
    "BaseVerificationStrategy",
    "VerificationStrategy",
    "StrategyExecutionResult",
    "SourceEntailmentStrategy",
    "CrossSourceCorroborationStrategy",
    "ContradictionCheckStrategy",
    "QuoteCheckStrategy",
    "NumericalCheckStrategy",
    "TemporalCheckStrategy",
    "HistoriographicalCheckStrategy",
    # Engine & Dispatch
    "STRATEGY_DISPATCH_MAP",
    "VerificationResult",
    "DossierVerificationReport",
    "VerificationEngine",
    # Script Verifier
    "DriftType",
    "DriftSeverity",
    "ScriptSentenceExtraction",
    "ScriptSentenceSegmenter",
    "ScriptClaimDriftRecord",
    "ScriptClaimMapping",
    "ScriptVerificationReport",
    "ScriptVerifier",
    # Visual Verifier
    "VisualSeverity",
    "VisualDiscrepancyType",
    "VisualInconsistencyRecord",
    "VisualDiscrepancy",
    "SceneVisualReport",
    "VisualVerificationReport",
    "VisualVerifier",
    # Numerical Pipeline
    "ChartType",
    "NumericalDataPoint",
    "NumericalDataset",
    "ChartElement",
    "ChartConfig",
    "NumericalTransformationRecord",
    "NumericalVerificationResult",
    "NumericalDatasetIngestion",
    "NumericalTransformer",
    "DeterministicChartRenderer",
    "NumericalInvariantChecker",
]
